{
 "title": "Rust Rest API",
 "description": "Dashboard providing real-time observability for the Rust REST API server. It tracks performance, resource usage, request throughput, error rates, and system health metrics to support monitoring, troubleshooting, and capacity planning.",
 "tags": [
  "rust",
  "server",
  "api",
  "rest-api"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus_ds", "query": "prometheus" },
   {
    "name": "job",
    "label": "Metrics Source",
    "query": {
     "query": "label_values(process_cpu_seconds_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Host",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"$job\"},instance)"
    }
   },
   {
    "name": "network_interface",
    "label": "Network Interface",
    "query": {
     "query": "process_system_network_received_bytes{instance=\"$instance\", job=\"$job\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "API Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Request",
   "type": "stat",
   "description": "Total number of requests made to the server within the range configured in the panel.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_requests_total{endpoint!~\"/api-docs/openapi.json|/health|/metrics\"}[$__range])))",
     "legendFormat": "Total number of requests made to the server"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "description": "Number of successful requests to the server within the range configured in the panel.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_requests_total{endpoint!~\"/favicon.ico|/swagger-ui|/api-docs/openapi.json|/metrics|/health\", status=~\"2..\"}[$__range])))",
     "legendFormat": "Number of successful requests"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "description": "Number of failed server requests within the range configured in the panel.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_requests_total{endpoint!~\"/favicon.ico|/swagger-ui|/api-docs/openapi.json|/metrics|/health\", status=~\"4..|5..\"}[$__range])))",
     "legendFormat": "Number of failed server requests"
    }
   ]
  },
  {
   "title": "Avarege Response Time Seconds (RTS)",
   "type": "timeseries",
   "description": "Average response time of a request.\nMeasures the mean duration a request takes to be processed, helping assess overall API performance and latency.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_duration_seconds_sum{endpoint!~\"/favicon.ico|/swagger-ui|/api-docs/openapi.json|/metrics|/health\"}[$__range])) by (endpoint) / sum(increase(http_requests_duration_seconds_count{endpoint!~\"/favicon.ico|/swagger-ui|/api-docs/openapi.json|/metrics|/health\"}[$__range])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Request per seconds (RPS)",
   "type": "timeseries",
   "description": "Average response time of a request.\nMeasures the mean duration a request takes to be processed, helping assess overall API performance and latency.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "increase(http_requests_duration_seconds_count{endpoint!~\"/favicon.ico|/swagger-ui|/api-docs/openapi.json|/metrics|/health\"}[$__range])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Response Status Rate",
   "type": "timeseries",
   "description": "Displays the response rate grouped by HTTP status codes, helping identify performance patterns and error spikes.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(http_requests_duration_seconds_count{endpoint!~\"/favicon.ico|/swagger-ui|/api-docs/openapi.json|/metrics|/health\", status=~\"2..|4..|5..\"}[$__range])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "System Memory Usage (%)",
   "type": "gauge",
   "description": "This panel displays the percentage of total system memory currently in use, providing a clear view of overall memory consumption and helping to identify potential resource constraints or memory pressure.",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_system_memory_usage{instance=\"$instance\", job=\"$job\"}/process_system_total_memory{instance=\"$instance\", job=\"$job\"}*100",
     "legendFormat": "System Memory Usage"
    }
   ]
  },
  {
   "title": "System Memory Usage in Bytes",
   "type": "timeseries",
   "description": "This panel displays the total system memory currently in use in bytes, providing a clear view of overall memory consumption and helping to identify potential resource constraints or memory pressure.",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_system_memory_usage{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "System Memory Usage"
    }
   ]
  },
  {
   "title": "Server Resident Memory (RSS)",
   "type": "timeseries",
   "description": "Displays the resident memory (RSS) used by the Rust service, showing how much physical RAM the process is currently occupying. Useful for tracking memory growth, spotting leaks, and monitoring overall resource usage.",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Server Resident Memory Size"
    }
   ]
  },
  {
   "title": "Server Virtual Memory",
   "type": "timeseries",
   "description": "Tracks the amount of virtual memory allocated by the Rust application, including memory reserved but not necessarily used. Useful for identifying memory growth, fragmentation, or abnormal allocation patterns.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Virtual Memory Size"
    }
   ]
  },
  { "title": "Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU Core Count",
   "type": "stat",
   "description": "Displays the total number of CPU cores available on the host system, indicating the processing capacity that can be used by the application and the operating system.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_system_cpu_count{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global CPU Usage (%)",
   "type": "gauge",
   "description": "Shows the percentage of CPU currently in use, representing how much of the available processing capacity is being consumed over time.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_total_cpu_usage{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Opened Descriptors"
    }
   ]
  },
  {
   "title": "Process CPU Time",
   "type": "stat",
   "description": "Displays the CPU time (user and system) used by the process on which the Server is running in seconds.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Process CPU Time"
    }
   ]
  },
  {
   "title": "Global CPU Usage (%)",
   "type": "timeseries",
   "description": "Shows the percentage of CPU currently in use all cores (global), representing how much of the available processing capacity is being consumed over time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_total_cpu_usage{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "CPU Usage (%)"
    }
   ]
  },
  {
   "title": "CPU Usage per Core (%)",
   "type": "timeseries",
   "description": "Shows the percentage of CPU currently in use per core, representing how much of the available processing capacity is being consumed over time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_system_cpu_usage_per_core{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{core}}"
    }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "stat",
   "description": "Timestamp indicating when the process started, represented as seconds since the Unix epoch.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Server Uptime"
    }
   ]
  },
  {
   "title": "Server Thread Count",
   "type": "stat",
   "description": "Represents the number of active threads used by the server, helping monitor concurrency levels and detect overload or thread-related bottlenecks.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_threads{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Server Thread Count"
    }
   ]
  },
  {
   "title": "Number of Open File Descriptors",
   "type": "stat",
   "description": "Number of file descriptors currently opened by the process. This metric helps monitor resource usage and detect potential file descriptor leaks, high I/O load, or limits being approached on the operating system.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Number of Open File Descriptors"
    }
   ]
  },
  {
   "title": "File Descriptors Usage",
   "type": "gauge",
   "description": "Percentage of the number of file descriptors currently opened by the process. This metric helps monitor resource usage and detect potential file descriptor leaks, high I/O load, or limits being approached on the operating system.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\",job=\"$job\"} / process_max_fds{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Opened Descriptors"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Received Bytes",
   "type": "timeseries",
   "description": "This panel displays the amount of data received across the available network interfaces. It helps monitor network throughput, identify traffic patterns, and detect potential bottlenecks or abnormal network usage in real time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_system_network_received_bytes{instance=\"$instance\", job=\"$job\", interface=~\"$network_interface\"}",
     "legendFormat": "Interface: {{interface}}"
    }
   ]
  },
  {
   "title": "Transmitted Bytes",
   "type": "timeseries",
   "description": "This panel displays the amount of data transmitted across the available network interfaces. It helps monitor network throughput, identify traffic patterns, and detect potential bottlenecks or abnormal network usage in real time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_system_network_transmitted_bytes{instance=\"$instance\", job=\"$job\", interface=~\"$network_interface\"}",
     "legendFormat": "Interface: {{interface}}"
    }
   ]
  }
 ]
}