# (1) starting from scratch
FROM nexus:5005/busybox:latest

# (2) configure groups and users
USER 10001:10001

# (3) copying binary
WORKDIR /app
#RUN mkdir -p /app/assets
COPY --chown=10001:10001 --chmod=0755 ./.binaries/server /app/server
COPY --chown=10001:10001 ./assets/* /app/assets/

# (4) running binary
CMD ["/app/server", "--config-file=/app/assets/config.yaml", "run"]