name: Rust Microservices Pipeline

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main

jobs:
  build:
    # Run the build job on multiple operating systems and targets
    uses: ./.github/workflows/rust-build.yaml

  code-quality:
    needs: build
    # Run code quality checks and tests after the build job
    uses: ./.github/workflows/rust-test.yaml

  release:
    needs: build
    # Publish release artifacts to GitHub Releases
    uses: ./.github/workflows/rust-release.yaml

  # deploy:
  #   needs: build
  #   # Deploy the crate to crates.io
  #   uses: ./.github/workflows/rust-deploy.yaml
    
    

          