name: Rust Microservices Pipeline

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-publish-macro-crate:
    # Build and publish the procedural macro crate to ensure it compiles correctly
    uses: ./.github/workflows/rust-build-publish-macro-crate.yaml
    secrets:
      inherit

  build:
    needs: build-publish-macro-crate
    # Run the build job on multiple operating systems and targets
    uses: ./.github/workflows/rust-build.yaml

  code-quality:
    needs: build
    # Run code quality checks and tests after the build job
    uses: ./.github/workflows/rust-test.yaml

  release:
    needs: build
    # Publish release artifacts to GitHub Releases
    uses: ./.github/workflows/rust-release.yaml

  publish:
    needs: build
    # Deploy the crate to crates.io
    uses: ./.github/workflows/rust-deploy.yaml
    
    

          